"use client";

import Link from "next/link";
import { useEffect } from "react";
import { Home } from "lucide-react";

/**
 * Blurred Chicago map backdrop matching Figma's snazzy-image. The 40px CSS
 * blur destroys detail anyway, so the asset is shipped as a 1500×1500 webp
 * (~43KB) generated by `scripts/optimize-snazzy.mjs` from the original 6000²
 * PNG (5.7MB) — the visual is identical, the byte count is 130× smaller.
 */
export function PastelBackdrop() {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-0 overflow-hidden">
      <div
        className="absolute inset-0 scale-110 bg-cover bg-center"
        style={{
          backgroundImage: "url('/landing/snazzy-image.webp')",
          filter: "blur(40px)",
        }}
      />
    </div>
  );
}

export function HomeButton() {
  return (
    <Link
      href="/"
      aria-label="Back to homepage"
      className="absolute left-5 top-[max(56px,env(safe-area-inset-top))] z-30 flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#131311] shadow-[0_0_20px_rgba(0,0,0,0.12)] transition-transform hover:scale-105"
    >
      <Home className="h-5 w-5" />
    </Link>
  );
}

/**
 * Sparkle — exact path from Figma (file iNe6l0dUb3vqqaHZZCul6w, nodes
 * 6138:88493 / 6138:88507). Cushion-shape 4-point star with concave arc sides,
 * #FFB825 fill, white outset stroke, soft yellow glow.
 *
 * `size` accepts a number (px) or any CSS length string (e.g. `"clamp(...)"`)
 * so the sparkle can scale responsively alongside the sticker.
 */
export function Sparkle({ size = 64, className }: { size?: number | string; className?: string }) {
  return (
    <svg
      viewBox="0 0 146 146"
      width={size}
      height={size}
      fill="none"
      aria-hidden
      className={className}
      style={{
        filter: "drop-shadow(0 0 12px rgba(255, 184, 37, 0.55))",
      }}
    >
      <path
        d="M73.0029 46C73.0024 46.068 73 46.136 73 46.2041C73 61.0028 85.0883 73 100 73C85.0883 73 73 84.9972 73 99.7959C73 99.864 73.0024 99.932 73.0029 100H72.9971C72.9976 99.932 73 99.864 73 99.7959C73 84.9972 60.9117 73 46 73C60.9117 73 73 61.0028 73 46.2041C73 46.136 72.9976 46.068 72.9971 46H73.0029Z"
        fill="#FFB825"
        stroke="#FFFFFF"
        strokeWidth={12}
        strokeLinejoin="round"
        paintOrder="stroke fill"
      />
    </svg>
  );
}

export function PrimaryButton({
  children,
  type = "button",
  disabled,
  onClick,
}: {
  children: React.ReactNode;
  type?: "button" | "submit";
  disabled?: boolean;
  onClick?: () => void;
}) {
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className="flex w-full items-center justify-center gap-2 rounded-full bg-[#131311] px-[18px] py-3 font-nunito text-[16px] font-bold tracking-[-0.24px] text-white transition-colors hover:bg-black disabled:cursor-not-allowed disabled:opacity-50"
    >
      {children}
    </button>
  );
}

/**
 * Bottom-anchored CTA container. Tracks visualViewport so it lifts above the
 * iOS soft keyboard (which doesn't shrink the layout viewport, leaving naive
 * `position: fixed` elements hidden under the keyboard).
 */
export function StickyCTA({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    const vv = typeof window !== "undefined" ? window.visualViewport : null;
    if (!vv) return;
    const root = document.documentElement;
    const update = () => {
      const offset = Math.max(0, window.innerHeight - vv.height - vv.offsetTop);
      root.style.setProperty("--keyboard-offset", `${offset}px`);
    };
    update();
    vv.addEventListener("resize", update);
    vv.addEventListener("scroll", update);
    return () => {
      vv.removeEventListener("resize", update);
      vv.removeEventListener("scroll", update);
      root.style.removeProperty("--keyboard-offset");
    };
  }, []);

  return (
    <div
      className="fixed inset-x-0 z-40 px-5 pb-3 pt-2"
      style={{
        bottom: "calc(env(safe-area-inset-bottom, 0px) + var(--keyboard-offset, 0px))",
      }}
    >
      <div className="mx-auto w-full max-w-[362px]">{children}</div>
    </div>
  );
}

export function StickyCTASpacer() {
  // CTA visible height ≈ button (46) + pt-2 + pb-3 = 66px. Add ~24px breathing
  // room above it plus safe-area-inset-bottom so tagline never crowds the CTA.
  return (
    <div
      aria-hidden
      className="shrink-0"
      style={{ height: "calc(96px + env(safe-area-inset-bottom, 0px))" }}
    />
  );
}
