"use client";

import Link from "next/link";
import { useEffect } from "react";
import { Home } from "lucide-react";

/**
 * Blurred Chicago map backdrop matching Figma's snazzy-image. The 40px CSS
 * blur destroys detail anyway, so the asset is shipped as a 1500×1500 webp
 * (~43KB) generated by `scripts/optimize-snazzy.mjs` from the original 6000²
 * PNG (5.7MB) — the visual is identical, the byte count is 130× smaller.
 */
export function PastelBackdrop() {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-0 overflow-hidden">
      <div
        className="absolute inset-0 scale-110 bg-cover bg-center"
        style={{
          backgroundImage: "url('/landing/snazzy-image.webp')",
          filter: "blur(40px)",
        }}
      />
    </div>
  );
}

export function HomeButton() {
  return (
    <Link
      href="/"
      aria-label="Back to homepage"
      className="absolute left-5 top-[max(56px,env(safe-area-inset-top))] z-30 flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#131311] shadow-[0_0_20px_rgba(0,0,0,0.12)] transition-transform hover:scale-105"
    >
      <Home className="h-5 w-5" />
    </Link>
  );
}

/**
 * Sparkle — exact path from Figma (file iNe6l0dUb3vqqaHZZCul6w, nodes
 * 6138:88493 / 6138:88507). Cushion-shape 4-point star with concave arc sides,
 * #FFB825 fill, white outset stroke, soft yellow glow.
 *
 * `size` accepts a number (px) or any CSS length string (e.g. `"clamp(...)"`)
 * so the sparkle can scale responsively alongside the sticker.
 */
export function Sparkle({ size = 64, className }: { size?: number | string; className?: string }) {
  return (
    <svg
      viewBox="0 0 146 146"
      width={size}
      height={size}
      fill="none"
      aria-hidden
      className={className}
      style={{
        filter: "drop-shadow(0 0 12px rgba(255, 184, 37, 0.55))",
      }}
    >
      <path
        d="M73.0029 46C73.0024 46.068 73 46.136 73 46.2041C73 61.0028 85.0883 73 100 73C85.0883 73 73 84.9972 73 99.7959C73 99.864 73.0024 99.932 73.0029 100H72.9971C72.9976 99.932 73 99.864 73 99.7959C73 84.9972 60.9117 73 46 73C60.9117 73 73 61.0028 73 46.2041C73 46.136 72.9976 46.068 72.9971 46H73.0029Z"
        fill="#FFB825"
        stroke="#FFFFFF"
        strokeWidth={12}
        strokeLinejoin="round"
        paintOrder="stroke fill"
      />
    </svg>
  );
}

/**
 * Liquid-glass variant palette — mirrors the RN GLASS palette in
 * mobile-frontend's FloatingPlusButton.tsx + Figma nodes 7490:56364 (Send,
 * normal-light) and 7575:26797 (Important, gold). Dark variants mirror the
 * structure with the dark-glass / navy hue.
 */
export type GlassVariant = "normal-light" | "normal-dark" | "important-light" | "important-dark";

export const GLASS_PALETTES: Record<
  GlassVariant,
  {
    fill: string;
    border: string;
    bottomInset: string;
    sideLight: string;
    text: string;
    textShadow: string;
    iconShadow: string;
  }
> = {
  "normal-light": {
    fill: "#f3f2f1",
    border: "#c9c7c4",
    bottomInset: "#dfdfdf",
    sideLight: "rgba(255, 255, 255, 0.4)",
    text: "#131311",
    textShadow: "0.5px 0.5px 0 #ffffff",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(255, 255, 255, 0.9))",
  },
  "normal-dark": {
    fill: "#424242",
    border: "#2b2b2b",
    bottomInset: "#2b2b2b",
    sideLight: "rgba(255, 255, 255, 0.1)",
    text: "#ffffff",
    textShadow: "0.5px 0.5px 0 rgba(0, 0, 0, 0.6)",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(0, 0, 0, 0.6))",
  },
  "important-light": {
    fill: "#fff6e2",
    border: "#e3c291",
    bottomInset: "#eddeb4",
    sideLight: "rgba(255, 255, 255, 0.4)",
    text: "#835300",
    textShadow: "0.5px 0.5px 0 #ffffff",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(255, 255, 255, 0.9))",
  },
  "important-dark": {
    fill: "#2c3a5e",
    border: "#1d2742",
    bottomInset: "#1d2742",
    sideLight: "rgba(255, 255, 255, 0.1)",
    text: "#c8d6f5",
    textShadow: "0.5px 0.5px 0 rgba(0, 0, 0, 0.6)",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(0, 0, 0, 0.6))",
  },
};

/**
 * Liquid-glass primary button — pixel-exact reconstruction of the Send pill
 * variant from Figma (file iNe6l0dUb3vqqaHZZCul6w, node 7490:56364 + its inner
 * frames 7490:56360 / 7490:56366).
 *
 * The visual depth comes from FIVE layers nested in order, mirroring the
 * original Figma structure exactly. Stacking them in JSX (vs. piling every
 * shadow onto one element) lets the two inset shadows live on DIFFERENT
 * bounding boxes — that's what gives the embossed pill its asymmetric
 * read (bottom darkening spans the full pill width, side highlights are
 * pinched to the narrower inner content row).
 *
 *   1. Outer <button>          1px stroke, rounded full, no fill
 *   2. Frame B                 fill + drop-shadow 1/2/1 rgba(0,0,0,0.1)
 *   3. Frame C (padded)        fill + px-[18px] py-[12px] gap-2 + text-shadow
 *                              0.5/0.5/0 (no blur) + icon drop-shadow filter
 *                              applied via [&_svg]:[filter:...]
 *   4. Side-highlight overlay  inside Frame C, inset ±8/0/8 sideLight
 *                              — bounds = Frame C's narrower inner box
 *   5. Bottom-shadow overlay   inside Frame B, inset 0/-13/13.5 bottomInset
 *                              — bounds = Frame B's full pill width
 *
 * `variant` switches the four palettes (normal-light/dark, important-
 * light/dark). All shadow / color / typography values are 1:1 Figma — never
 * amplify or tweak.
 */
export function PrimaryButton({
  children,
  type = "button",
  disabled,
  onClick,
  form,
  fullWidth = true,
  variant = "normal-light",
}: {
  children: React.ReactNode;
  type?: "button" | "submit";
  disabled?: boolean;
  onClick?: () => void;
  form?: string;
  /**
   * When true (default) the button stretches to its container's width — used
   * by the StickyCTA-mounted form buttons. Set false for inline call-sites
   * (e.g. the ClaimFlow retry button) so the pill hugs its content like the
   * Figma Send variant does.
   */
  fullWidth?: boolean;
  variant?: GlassVariant;
}) {
  const p = GLASS_PALETTES[variant];
  return (
    <button
      type={type}
      form={form}
      onClick={onClick}
      disabled={disabled}
      className={`${
        fullWidth ? "block w-full" : "inline-block"
      } rounded-full border bg-transparent p-0 transition-transform duration-150 ease-out hover:scale-[1.01] active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:scale-100`}
      style={
        {
          borderColor: p.border,
          // CSS variable so the descendant `[&_svg]` selector below can
          // inherit the icon shadow without each SVG needing its own filter.
          ["--liquid-icon-shadow" as string]: p.iconShadow,
        } as React.CSSProperties
      }
    >
      {/* Frame B — fill + drop shadow. 1:1 Figma. */}
      <span
        className={`relative block rounded-full ${fullWidth ? "w-full" : ""}`}
        style={{
          backgroundColor: p.fill,
          filter: "drop-shadow(1px 2px 1px rgba(0, 0, 0, 0.1))",
        }}
      >
        {/* Frame C — padded inner row with content + text-shadow + icon
            drop-shadow (applied to all <svg> descendants). 1:1 Figma. */}
        <span
          className={`relative flex items-center justify-center gap-2 rounded-full px-[18px] py-[12px] font-nunito text-[16px] font-bold tracking-[-0.24px] [&_svg]:[filter:var(--liquid-icon-shadow)] ${
            fullWidth ? "w-full" : ""
          }`}
          style={{
            backgroundColor: p.fill,
            color: p.text,
            textShadow: p.textShadow,
          }}
        >
          <span className="relative z-10 inline-flex items-center gap-2">{children}</span>
          {/* Side highlights — Frame C bounds. 1:1 Figma. */}
          <span
            aria-hidden
            className="pointer-events-none absolute inset-0 rounded-full"
            style={{
              boxShadow: `inset -8px 0px 8px 0px ${p.sideLight}, inset 8px 0px 8px 0px ${p.sideLight}`,
            }}
          />
        </span>
        {/* Bottom dark inset — Frame B bounds. 1:1 Figma. */}
        <span
          aria-hidden
          className="pointer-events-none absolute inset-0 rounded-full"
          style={{ boxShadow: `inset 0px -13px 13.5px 0px ${p.bottomInset}` }}
        />
      </span>
    </button>
  );
}

/**
 * Bottom-anchored CTA container. Tracks visualViewport so it lifts above the
 * iOS soft keyboard (which doesn't shrink the layout viewport, leaving naive
 * `position: fixed` elements hidden under the keyboard).
 */
export function StickyCTA({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    const vv = typeof window !== "undefined" ? window.visualViewport : null;
    if (!vv) return;
    const root = document.documentElement;
    const update = () => {
      const offset = Math.max(0, window.innerHeight - vv.height - vv.offsetTop);
      root.style.setProperty("--keyboard-offset", `${offset}px`);
    };
    update();
    vv.addEventListener("resize", update);
    vv.addEventListener("scroll", update);
    return () => {
      vv.removeEventListener("resize", update);
      vv.removeEventListener("scroll", update);
      root.style.removeProperty("--keyboard-offset");
    };
  }, []);

  return (
    <div
      className="fixed inset-x-0 z-40 px-5 pb-3 pt-2"
      style={{
        bottom: "calc(env(safe-area-inset-bottom, 0px) + var(--keyboard-offset, 0px))",
      }}
    >
      <div className="mx-auto w-full max-w-[362px]">{children}</div>
    </div>
  );
}

export function StickyCTASpacer() {
  // CTA visible height ≈ button (46) + pt-2 + pb-3 = 66px. Add ~24px breathing
  // room above it plus safe-area-inset-bottom so tagline never crowds the CTA.
  return (
    <div
      aria-hidden
      className="shrink-0"
      style={{ height: "calc(96px + env(safe-area-inset-bottom, 0px))" }}
    />
  );
}
