"use client";

import Link from "next/link";
import { useEffect } from "react";
import { Home } from "lucide-react";

/**
 * Blurred Chicago map backdrop matching Figma's snazzy-image. The 40px CSS
 * blur destroys detail anyway, so the asset is shipped as a 1500×1500 webp
 * (~43KB) generated by `scripts/optimize-snazzy.mjs` from the original 6000²
 * PNG (5.7MB) — the visual is identical, the byte count is 130× smaller.
 */
export function PastelBackdrop() {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-0 overflow-hidden">
      <div
        className="absolute inset-0 scale-110 bg-cover bg-center"
        style={{
          backgroundImage: "url('/landing/snazzy-image.webp')",
          filter: "blur(40px)",
        }}
      />
    </div>
  );
}

export function HomeButton() {
  return (
    <Link
      href="/"
      aria-label="Back to homepage"
      className="absolute left-5 top-[max(56px,env(safe-area-inset-top))] z-30 flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#131311] shadow-[0_0_20px_rgba(0,0,0,0.12)] transition-transform hover:scale-105"
    >
      <Home className="h-5 w-5" />
    </Link>
  );
}

/**
 * Sparkle — exact path from Figma (file iNe6l0dUb3vqqaHZZCul6w, nodes
 * 6138:88493 / 6138:88507). Cushion-shape 4-point star with concave arc sides,
 * #FFB825 fill, white outset stroke, soft yellow glow.
 *
 * `size` accepts a number (px) or any CSS length string (e.g. `"clamp(...)"`)
 * so the sparkle can scale responsively alongside the sticker.
 */
export function Sparkle({ size = 64, className }: { size?: number | string; className?: string }) {
  return (
    <svg
      viewBox="0 0 146 146"
      width={size}
      height={size}
      fill="none"
      aria-hidden
      className={className}
      style={{
        filter: "drop-shadow(0 0 12px rgba(255, 184, 37, 0.55))",
      }}
    >
      <path
        d="M73.0029 46C73.0024 46.068 73 46.136 73 46.2041C73 61.0028 85.0883 73 100 73C85.0883 73 73 84.9972 73 99.7959C73 99.864 73.0024 99.932 73.0029 100H72.9971C72.9976 99.932 73 99.864 73 99.7959C73 84.9972 60.9117 73 46 73C60.9117 73 73 61.0028 73 46.2041C73 46.136 72.9976 46.068 72.9971 46H73.0029Z"
        fill="#FFB825"
        stroke="#FFFFFF"
        strokeWidth={12}
        strokeLinejoin="round"
        paintOrder="stroke fill"
      />
    </svg>
  );
}

/**
 * Liquid-glass variant palette — mirrors the RN GLASS palette in
 * mobile-frontend's FloatingPlusButton.tsx + Figma nodes 7490:56364 (Send,
 * normal-light) and 7575:26797 (Important, gold). Dark variants mirror the
 * structure with the dark-glass / navy hue.
 */
export type GlassVariant = "normal-light" | "normal-dark" | "important-light" | "important-dark";

export interface GlassPalette {
  fill: string;
  border: string;
  bottomInset: string;
  sideLight: string;
  text: string;
  textShadow: string;
  iconShadow: string;
  /**
   * Outer drop-shadow color for both resting and hover state. Light variants
   * use Figma's `rgba(0,0,0,0.1)` exact. Dark variants use 0.4 alpha — on a
   * dark fill a 10% black shadow vanishes so the hover lift wouldn't read.
   */
  dropShadowRgba: string;
  /**
   * "Back wall" — fills Frame A (outermost) behind the Frame B button surface.
   * Visible only in the 2px hover-lift gap; reads as the dark side face of a
   * 3D button rising. Without it, dark variants showed map/page background
   * through the gap ("镂空", hollowed out).
   */
  wallColor: string;
}

export const GLASS_PALETTES: Record<GlassVariant, GlassPalette> = {
  "normal-light": {
    fill: "#f3f2f1",
    border: "#c9c7c4",
    bottomInset: "#dfdfdf",
    sideLight: "rgba(255, 255, 255, 0.4)",
    text: "#131311",
    textShadow: "0.5px 0.5px 0 #ffffff",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(255, 255, 255, 0.9))",
    dropShadowRgba: "rgba(0, 0, 0, 0.1)",
    // White variant wall — light grey just darker than the #f3f2f1 fill. The
    // first pass at #a9a7a4 read as too harsh against the white surroundings.
    wallColor: "#cdcbc8",
  },
  "normal-dark": {
    fill: "#424242",
    border: "#2b2b2b",
    bottomInset: "#2b2b2b",
    sideLight: "rgba(255, 255, 255, 0.1)",
    text: "#ffffff",
    textShadow: "0.5px 0.5px 0 rgba(0, 0, 0, 0.6)",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(0, 0, 0, 0.6))",
    dropShadowRgba: "rgba(0, 0, 0, 0.4)",
    // User: 黑色要更深的黑色 — much darker than the #424242 fill.
    wallColor: "#0a0a0a",
  },
  "important-light": {
    fill: "#fff6e2",
    border: "#e3c291",
    bottomInset: "#eddeb4",
    sideLight: "rgba(255, 255, 255, 0.4)",
    text: "#835300",
    textShadow: "0.5px 0.5px 0 #ffffff",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(255, 255, 255, 0.9))",
    dropShadowRgba: "rgba(0, 0, 0, 0.1)",
    // Darker gold to match the variant's brown text identity.
    wallColor: "#a47a3a",
  },
  "important-dark": {
    fill: "#2c3a5e",
    border: "#1d2742",
    bottomInset: "#1d2742",
    sideLight: "rgba(255, 255, 255, 0.1)",
    text: "#c8d6f5",
    textShadow: "0.5px 0.5px 0 rgba(0, 0, 0, 0.6)",
    iconShadow: "drop-shadow(0.5px 0.5px 0 rgba(0, 0, 0, 0.6))",
    dropShadowRgba: "rgba(0, 0, 0, 0.4)",
    // Much darker navy than #2c3a5e fill.
    wallColor: "#0a1024",
  },
};

/**
 * Inner pill renderer — frames B/C + the two inset overlays, the visual
 * "body" of the Liquid Glass button. Both `PrimaryButton` (`<button>` form
 * submits) and `LiquidGlassPill` (`<a>` link-style CTA in `LandingHero`)
 * wrap this same body — there is exactly ONE source of truth for the
 * hover physics, easing, palette wiring, and Figma 5-layer structure. Fix
 * a hover bug here, both surfaces pick it up.
 *
 * Pill anatomy (1:1 Figma node 7490:56364):
 *
 *   1. Outer wrapper (caller — <button> / <a>)  1px stroke, wallColor fill,
 *                                               group/pill hover scope
 *   2. Frame B (here)             fill + box-shadow 1/2/1 (CSS var driven)
 *   3. Frame C (padded)           fill + px-[18px] py-[12px] gap-2 + text-shadow
 *                                 + icon drop-shadow filter ([&_svg]:filter)
 *   4. Side-highlight overlay     inset ±8/0/8 sideLight — Frame C bounds
 *   5. Bottom-shadow overlay      inset 0/-13/13.5 bottomInset — Frame B bounds
 *
 * Hover physics:
 *   transform: translateY(0) → translateY(-2px)
 *   box-shadow: 1px 2px 1px → 1px 4px 1px  (Y offset only)
 *
 * Easing was previously `cubic-bezier(0.34, 1.56, 0.64, 1)` ("easeOutBack",
 * peaks at y≈1.56) — visually the button overshot ~5% past its -2px target,
 * then settled. Read on screen as two distinct motions ("button lifts →
 * angle change → settles") even though it's one curve. Replaced with
 * `cubic-bezier(0.2, 0.8, 0.2, 1)` — smooth ease-out, no overshoot, monotonic
 * settle. The lift + shadow now register as ONE continuous motion to the eye.
 */
function PillBody({
  children,
  palette,
  fullWidth,
}: {
  children: React.ReactNode;
  palette: GlassPalette;
  fullWidth: boolean;
}) {
  return (
    <span
      className={`relative block rounded-full transition-[transform,box-shadow] duration-[260ms] ease-[cubic-bezier(0.2,0.8,0.2,1)] shadow-[1px_2px_1px_var(--pill-shadow-rgba)] group-hover/pill:shadow-[1px_4px_1px_var(--pill-shadow-rgba)] group-hover/pill:-translate-y-[2px] ${
        fullWidth ? "w-full" : ""
      }`}
      style={{ backgroundColor: palette.fill }}
    >
      <span
        className={`relative flex items-center justify-center gap-2 rounded-full px-[18px] py-[12px] font-nunito text-[16px] font-bold tracking-[-0.24px] [&_svg]:[filter:var(--liquid-icon-shadow)] ${
          fullWidth ? "w-full" : ""
        }`}
        style={{
          backgroundColor: palette.fill,
          color: palette.text,
          textShadow: palette.textShadow,
        }}
      >
        <span className="relative z-10 inline-flex items-center gap-2">{children}</span>
        <span
          aria-hidden
          className="pointer-events-none absolute inset-0 rounded-full"
          style={{
            boxShadow: `inset -8px 0px 8px 0px ${palette.sideLight}, inset 8px 0px 8px 0px ${palette.sideLight}`,
          }}
        />
      </span>
      <span
        aria-hidden
        className="pointer-events-none absolute inset-0 rounded-full"
        style={{ boxShadow: `inset 0px -13px 13.5px 0px ${palette.bottomInset}` }}
      />
    </span>
  );
}

/** Outer wrapper style (border, wallColor, CSS vars) shared by both button
 *  + anchor variants — same single source of truth for the pill chrome.
 *  Returns a style object so callers can spread it on their own element. */
export function pillWrapperStyle(palette: GlassPalette): React.CSSProperties {
  return {
    borderColor: palette.border,
    // Wall color visible only in the 2px lift gap on hover — the side face
    // of the 3D button rising. At rest, Frame B covers it.
    backgroundColor: palette.wallColor,
    ["--liquid-icon-shadow" as string]: palette.iconShadow,
    ["--pill-shadow-rgba" as string]: palette.dropShadowRgba,
  } as React.CSSProperties;
}

/**
 * Liquid-glass primary button — `<button>` form-submit variant. The visual
 * body comes from `<PillBody>`, the same component `LiquidGlassPill` (the
 * `<a>` variant in LandingHero) uses — one source of truth for hover
 * physics + palette wiring across both surfaces.
 */
export function PrimaryButton({
  children,
  type = "button",
  disabled,
  onClick,
  form,
  fullWidth = true,
  variant = "normal-light",
}: {
  children: React.ReactNode;
  type?: "button" | "submit";
  disabled?: boolean;
  onClick?: () => void;
  form?: string;
  fullWidth?: boolean;
  variant?: GlassVariant;
}) {
  const p = GLASS_PALETTES[variant];
  return (
    <button
      type={type}
      form={form}
      onClick={onClick}
      disabled={disabled}
      className={`group/pill ${
        fullWidth ? "block w-full" : "inline-block"
      } rounded-full border p-0 disabled:cursor-not-allowed disabled:opacity-50`}
      style={pillWrapperStyle(p)}
    >
      <PillBody palette={p} fullWidth={fullWidth}>
        {children}
      </PillBody>
    </button>
  );
}

/**
 * Liquid-glass CTA pill — `<a>` href-driven variant for landing-hero CTAs
 * ("Join waitlist", "Work with us"). Reuses `<PillBody>` — same body, same
 * hover, only the outer element differs.
 */
export function LiquidGlassPill({
  href,
  children,
  ariaLabel,
  external,
  variant = "normal-light",
}: {
  href: string;
  children: React.ReactNode;
  ariaLabel?: string;
  external?: boolean;
  variant?: GlassVariant;
}) {
  const p = GLASS_PALETTES[variant];
  return (
    <a
      href={href}
      aria-label={ariaLabel}
      target={external ? "_blank" : undefined}
      rel={external ? "noopener noreferrer" : undefined}
      className="group/pill btn--link inline-block rounded-full border p-0 no-underline"
      style={pillWrapperStyle(p)}
    >
      <PillBody palette={p} fullWidth={false}>
        {children}
      </PillBody>
    </a>
  );
}

/**
 * Bottom-anchored CTA container. Tracks visualViewport so it lifts above the
 * iOS soft keyboard (which doesn't shrink the layout viewport, leaving naive
 * `position: fixed` elements hidden under the keyboard).
 */
export function StickyCTA({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    const vv = typeof window !== "undefined" ? window.visualViewport : null;
    if (!vv) return;
    const root = document.documentElement;
    const update = () => {
      const offset = Math.max(0, window.innerHeight - vv.height - vv.offsetTop);
      root.style.setProperty("--keyboard-offset", `${offset}px`);
    };
    update();
    vv.addEventListener("resize", update);
    vv.addEventListener("scroll", update);
    return () => {
      vv.removeEventListener("resize", update);
      vv.removeEventListener("scroll", update);
      root.style.removeProperty("--keyboard-offset");
    };
  }, []);

  return (
    <div
      className="fixed inset-x-0 z-40 px-5 pb-3 pt-2"
      style={{
        bottom: "calc(env(safe-area-inset-bottom, 0px) + var(--keyboard-offset, 0px))",
      }}
    >
      <div className="mx-auto w-full max-w-[362px]">{children}</div>
    </div>
  );
}

export function StickyCTASpacer() {
  // CTA visible height ≈ button (46) + pt-2 + pb-3 = 66px. Add ~24px breathing
  // room above it plus safe-area-inset-bottom so tagline never crowds the CTA.
  return (
    <div
      aria-hidden
      className="shrink-0"
      style={{ height: "calc(96px + env(safe-area-inset-bottom, 0px))" }}
    />
  );
}
